attribution:
    Abdurrahman Rajab:
        - rajab-2@windowslive.com
    Anush:
        - anushshetty90@gmail.com
    Anush008:
        - anushshetty90@gmail.com
    Aryaman Sharma:
        - 72215253+TheLazron@users.noreply.github.com
    Ayu Adiati:
        - 45172775+adiati98@users.noreply.github.com
    BekahHW:
        - 34313413+BekahHW@users.noreply.github.com
    Brian 'bdougie' Douglas:
        - brian@opensauced.pizza
    Brian Douglas:
        - bdougie@users.noreply.github.com
    Christine Belzie:
        - shecoder30@gmail.com
        - 105683440+CBID2@users.noreply.github.com
    Divyansh Singh:
        - divyanshanandsingh@gmail.com
    Jasmine:
        - 105261487+codewithjazzy@users.noreply.github.com
    John McBride:
        - jpmmcbride@gmail.com
        - john@opensauced.pizza
    Marcus Chan:
        - 47471007+marcusgchan@users.noreply.github.com
        - marcuscchan@gmail.com
    Nanak:
        - 36790357+Nanak360@users.noreply.github.com
    Nick Taylor:
        - nick@iamdeveloper.com
        - nick@nickyt.co
    Ozgur Sar:
        - ozgursar77@gmail.com
    Pratham:
        - prathamsinghal2003@gmail.com
    Punyam Singh:
        - 89277920+punyamsingh@users.noreply.github.com
    Susmita-Dey:
        - susmitadey475@gmail.com
    dependabot[bot]:
        - 49699333+dependabot[bot]@users.noreply.github.com
    doaortu:
        - 113872927+doaortu@users.noreply.github.com
        - yunawita.peni@outlook.com
    mtfoley:
        - mtfoley.mae@gmail.com
    punyamsingh:
        - 89277920+punyamsingh@users.noreply.github.com
attribution-fallback: []