attribution:
    a0m0rajab:
        - rajab-2@windowslive.com
    Anush008:
        - anushshetty90@gmail.com
        - anushshetty90@gmail.com
    BekahHW:
        - 34313413+BekahHW@users.noreply.github.com
    bdougie:
        - brian@opensauced.pizza
        - bdougie@users.noreply.github.com
    diivi:
        - divyanshanandsingh@gmail.com
    jpmcb:
        - jpmmcbride@gmail.com
        - john@opensauced.pizza
    nickytonline:
        - nick@iamdeveloper.com
        - nick@nickyt.co
attribution-fallback: 
    - open-sauced/engineering
