name: Playwright Tests
on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "🔧 setup Bun"
      uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      run: bun install
    - name: Install Playwright Browsers
      run: bun x playwright install --with-deps
    - name: Run Playwright tests
      run: bun x playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
